/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.guestbook.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GuestBook service. Represents a row in the &quot;GB_GuestBook&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.guestbook.model.impl.GuestBookModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.guestbook.model.impl.GuestBookImpl</code>.
 * </p>
 *
 * @author liferay
 * @see GuestBook
 * @generated
 */
@ProviderType
public interface GuestBookModel
	extends BaseModel<GuestBook>, GroupedModel, MVCCModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a guest book model instance should use the {@link GuestBook} interface instead.
	 */

	/**
	 * Returns the primary key of this guest book.
	 *
	 * @return the primary key of this guest book
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this guest book.
	 *
	 * @param primaryKey the primary key of this guest book
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this guest book.
	 *
	 * @return the mvcc version of this guest book
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this guest book.
	 *
	 * @param mvccVersion the mvcc version of this guest book
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this guest book.
	 *
	 * @return the uuid of this guest book
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this guest book.
	 *
	 * @param uuid the uuid of this guest book
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the guestbook ID of this guest book.
	 *
	 * @return the guestbook ID of this guest book
	 */
	public long getGuestbookId();

	/**
	 * Sets the guestbook ID of this guest book.
	 *
	 * @param guestbookId the guestbook ID of this guest book
	 */
	public void setGuestbookId(long guestbookId);

	/**
	 * Returns the name of this guest book.
	 *
	 * @return the name of this guest book
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this guest book.
	 *
	 * @param name the name of this guest book
	 */
	public void setName(String name);

	/**
	 * Returns the group ID of this guest book.
	 *
	 * @return the group ID of this guest book
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this guest book.
	 *
	 * @param groupId the group ID of this guest book
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this guest book.
	 *
	 * @return the company ID of this guest book
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this guest book.
	 *
	 * @param companyId the company ID of this guest book
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this guest book.
	 *
	 * @return the user ID of this guest book
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this guest book.
	 *
	 * @param userId the user ID of this guest book
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this guest book.
	 *
	 * @return the user uuid of this guest book
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this guest book.
	 *
	 * @param userUuid the user uuid of this guest book
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this guest book.
	 *
	 * @return the user name of this guest book
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this guest book.
	 *
	 * @param userName the user name of this guest book
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this guest book.
	 *
	 * @return the create date of this guest book
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this guest book.
	 *
	 * @param createDate the create date of this guest book
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this guest book.
	 *
	 * @return the modified date of this guest book
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this guest book.
	 *
	 * @param modifiedDate the modified date of this guest book
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this guest book.
	 *
	 * @return the status of this guest book
	 */
	public int getStatus();

	/**
	 * Sets the status of this guest book.
	 *
	 * @param status the status of this guest book
	 */
	public void setStatus(int status);

	/**
	 * Returns the status by ID of this guest book.
	 *
	 * @return the status by ID of this guest book
	 */
	public long getStatusById();

	/**
	 * Sets the status by ID of this guest book.
	 *
	 * @param statusById the status by ID of this guest book
	 */
	public void setStatusById(long statusById);

	/**
	 * Returns the status by user name of this guest book.
	 *
	 * @return the status by user name of this guest book
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this guest book.
	 *
	 * @param statusByUserName the status by user name of this guest book
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this guest book.
	 *
	 * @return the status date of this guest book
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this guest book.
	 *
	 * @param statusDate the status date of this guest book
	 */
	public void setStatusDate(Date statusDate);

}